version: '3.4'

services:
  micro-c-web.server:
    image: ${DOCKER_REGISTRY-}microcwebserver
    build:
      context: .
      dockerfile: micro-c-web/Server/Dockerfile
    environment:
      Secrets__DbPassword: "password123!@#"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "password123!@#"
      ACCEPT_EULA: "Y"